[phases.setup]
nixPkgs = ["python311", "playwright-driver"]

[phases.build]
cmds = ["pip install -r requirements.txt", "PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium"]

[start]
cmd = "python bot.py"
